#! /bin/bash

domain=$1
rm /etc/prosody/conf.d/${domain}.cfg.lua
rm /etc/prosody/conf.avail/${domain}.cfg.lua
rm /etc/nginx/conf.d/${domain}-extra-xmpp.conf
systemctl restart prosody
systemctl reload nginx
