#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

domains=$(yunohost domain list --exclude-subdomains | grep -Ev '^(domains|main):' | awk '{print $2}')

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

for domain in ${domains} ; do
	rm /etc/prosody/conf.d/${domain}.cfg.lua
	rm /etc/prosody/conf.avail/${domain}.cfg.lua
	rm /etc/nginx/conf.d/${domain}-extra-xmpp.conf
done

ynh_systemctl --service=nginx --action="reload"

#=================================================
# REMOVE PACKAGES
#=================================================

DEBIAN_FRONTEND=noninteractive apt-get remove --assume-yes prosody

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
